// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0EWBFwjMY7AQA5hxf8V6nGDKKxxMTBwQ',
    appId: '1:879259228713:web:3ca05d9baafd036127da38',
    messagingSenderId: '879259228713',
    projectId: 'nutri-lsa',
    authDomain: 'nutri-lsa.firebaseapp.com',
    storageBucket: 'nutri-lsa.firebasestorage.app',
    measurementId: 'G-3VYNVSTRCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW-FEPFZS5eu3lYO8Dv51I_aXWyUppY5Q',
    appId: '1:879259228713:android:ecc5b346fcc5c30527da38',
    messagingSenderId: '879259228713',
    projectId: 'nutri-lsa',
    storageBucket: 'nutri-lsa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABka9SPZOMl9V5qvNh3Ntq0llObysOJCk',
    appId: '1:879259228713:ios:20b6f53584a1509127da38',
    messagingSenderId: '879259228713',
    projectId: 'nutri-lsa',
    storageBucket: 'nutri-lsa.firebasestorage.app',
    iosBundleId: 'com.nutri.appoficial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABka9SPZOMl9V5qvNh3Ntq0llObysOJCk',
    appId: '1:879259228713:ios:20b6f53584a1509127da38',
    messagingSenderId: '879259228713',
    projectId: 'nutri-lsa',
    storageBucket: 'nutri-lsa.firebasestorage.app',
    iosBundleId: 'com.nutri.appoficial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0EWBFwjMY7AQA5hxf8V6nGDKKxxMTBwQ',
    appId: '1:879259228713:web:3ca05d9baafd036127da38',
    messagingSenderId: '879259228713',
    projectId: 'nutri-lsa',
    authDomain: 'nutri-lsa.firebaseapp.com',
    storageBucket: 'nutri-lsa.firebasestorage.app',
    measurementId: 'G-3VYNVSTRCM',
  );
}