// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0EWBFwjMY7AQA5hxf8V6nGDKKxxMTBwQ',
    appId: '1:879259228713:web:4421874c790124fb27da38',
    messagingSenderId: '879259228713',
    projectId: 'nutri-lsa',
    authDomain: 'nutri-lsa.firebaseapp.com',
    storageBucket: 'nutri-lsa.firebasestorage.app',
    measurementId: 'G-H660FERNJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW-FEPFZS5eu3lYO8Dv51I_aXWyUppY5Q',
    appId: '1:879259228713:android:ff166073f51097e627da38',
    messagingSenderId: '879259228713',
    projectId: 'nutri-lsa',
    storageBucket: 'nutri-lsa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNLmwdMRU8NjsbUHQWteL8of2ZGt7Ay80',
    appId: '1:330528185869:ios:ed91c47d9b6a8f67923f44',
    messagingSenderId: '330528185869',
    projectId: 'nutri-leche-chat',
    storageBucket: 'nutri-leche-chat.firebasestorage.app',
    iosBundleId: 'com.example.nutriLeche',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNLmwdMRU8NjsbUHQWteL8of2ZGt7Ay80',
    appId: '1:330528185869:ios:ed91c47d9b6a8f67923f44',
    messagingSenderId: '330528185869',
    projectId: 'nutri-leche-chat',
    storageBucket: 'nutri-leche-chat.firebasestorage.app',
    iosBundleId: 'com.example.nutriLeche',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzXGrtRFJBVdvFuyTO-VdtecIldcvGing',
    appId: '1:330528185869:web:a32ca1b79ae08f45923f44',
    messagingSenderId: '330528185869',
    projectId: 'nutri-leche-chat',
    authDomain: 'nutri-leche-chat.firebaseapp.com',
    storageBucket: 'nutri-leche-chat.firebasestorage.app',
    measurementId: 'G-SRQEF3WNZS',
  );
}
