// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzXGrtRFJBVdvFuyTO-VdtecIldcvGing',
    appId: '1:330528185869:web:2d86a5324d564018923f44',
    messagingSenderId: '330528185869',
    projectId: 'nutri-leche-chat',
    authDomain: 'nutri-leche-chat.firebaseapp.com',
    storageBucket: 'nutri-leche-chat.firebasestorage.app',
    measurementId: 'G-DZ9WY3SC3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALFoRoGnns0qkrvfX6t115vT5ell2Vesg',
    appId: '1:330528185869:android:35ec6248e309f2cb923f44',
    messagingSenderId: '330528185869',
    projectId: 'nutri-leche-chat',
    storageBucket: 'nutri-leche-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNLmwdMRU8NjsbUHQWteL8of2ZGt7Ay80',
    appId: '1:330528185869:ios:ed91c47d9b6a8f67923f44',
    messagingSenderId: '330528185869',
    projectId: 'nutri-leche-chat',
    storageBucket: 'nutri-leche-chat.firebasestorage.app',
    iosBundleId: 'com.example.nutriLeche',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNLmwdMRU8NjsbUHQWteL8of2ZGt7Ay80',
    appId: '1:330528185869:ios:ed91c47d9b6a8f67923f44',
    messagingSenderId: '330528185869',
    projectId: 'nutri-leche-chat',
    storageBucket: 'nutri-leche-chat.firebasestorage.app',
    iosBundleId: 'com.example.nutriLeche',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzXGrtRFJBVdvFuyTO-VdtecIldcvGing',
    appId: '1:330528185869:web:a32ca1b79ae08f45923f44',
    messagingSenderId: '330528185869',
    projectId: 'nutri-leche-chat',
    authDomain: 'nutri-leche-chat.firebaseapp.com',
    storageBucket: 'nutri-leche-chat.firebasestorage.app',
    measurementId: 'G-SRQEF3WNZS',
  );
}
